version: '3'
services:
  influxdb:
    image: influxdb:2.0
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data/:/var/lib/influxdb2
      - ./influxdb/config/:/etc/influxdb2/
    environment:
      - DOCKER_INFLUXDB_CONFIG_PATH=/etc/influxdb2/influxdb.conf